config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root 'pages#home'

  resources :charges

  resources :products, only: [:index]

  resources :purchases, only: [:show]
  

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/product.rb
class Product < ActiveRecord::Base
	def full_description
		"#{self.title} #{self.subtitle}"
	end

	def price_in_cents
		(self.price * 100).to_i
	end

	def thumbnail_image_name
		"product-#{title.split.slice(0..-2).join(" ").gsub(" ", "-").downcase}.png"
	end
end

app/models/purchase.rb
require 'securerandom'

class Purchase < ActiveRecord::Base
	after_create :email_purchaser

	def to_param
		uuid
	end

	private

	def email_purchaser
		PurchaseMailer.purchase_receipt(self).deliver
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
		def create
		product = Product.find(params[:product_id])

	  customer = Stripe::Customer.create(
	    :email => params[:stripeEmail],
	    :source  => params[:stripeToken],
	    :plan => "GROHACK2"
	  )

	  # charge = Stripe::Charge.create(
	  #   :customer    => customer.id,
	  #   :amount      => product.price_in_cents,
	  #   :description => product.full_description,
	  #   :currency    => 'usd'
	  # )

	  purchase = Purchase.create(email: params[:stripeEmail], card: params[:stripeToken],
	  	amount: product.price_in_cents, description: product.full_description, currency: 'usd',
	  	customer_id: customer.id, product_id: product.id, uuid: SecureRandom.uuid)

	  redirect_to purchase

	rescue Stripe::CardError => e
	  flash[:error] = e.message
	  redirect_to new_charge_path
	end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	def home
		@product = Product.find_by_sku("GROHACK2")
	end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
	def index
		@products = Product.all
	end
end

app/controllers/purchases_controller.rb
class PurchasesController < ApplicationController
	def show
		@purchase = Purchase.find_by_uuid(params[:id])
		@product = Product.find(@purchase.product_id)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/charges/create.html.erb
Purchase successful!

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ecommerce</title>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, user-scalable=no">
  <link rel='stylesheet' href='http://fonts.googleapis.com/css?family=Open+Sans:400,700,300,800' >
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<div id="content" class="container">
    <header id="content-header">
	    <div id="price-container">
	      <span class="glyphicon glyphicon-tag"></span><span class="price">$4.99</span>
	    </div>
	    <%= image_tag('header-image.jpg', id: 'content-header-img', alt: 'Learn Growth Hacking') %>
    </header>
		<%= yield %>
	</div>

</body>
</html>

app/views/layouts/purchase_mailer.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title>One Month Stripe Payments</title>
	</head>
	<body>
		
		<%= yield %>

		<p>Thanks for buying from us!</p>
	</body>
</html>

app/views/pages/home.html.erb
<section id="content-details" class="row clearfix">
  <article id="details-article" class="col-sm-8">
      <h1 id="article-title"><%= @product.title %> 
        <span class="font-weight-light"><%= @product.subtitle %></span></h1>
      <h3><small>By <a href="#" data-toggle="modal" data-target="#author-modal">
        <%= @product.author %></a></small></h3>

      <%= raw @product.description %>
  </article>
  <aside id="details-aside" class="col-sm-4">
    <%= form_tag charges_path, id:'chargeForm' do %>
      <article>
        <% if flash[:error].present? %>
          <div id="error_explanation">
            <p><%= flash[:error] %></p>
          </div>
        <% end %>
      </article>

      <script src="https://checkout.stripe.com/checkout.js"></script> 
      <%= hidden_field_tag 'stripeToken' %>
      <%= hidden_field_tag 'stripeEmail' %>
      <%= hidden_field_tag 'amount', @product.price_in_cents %>
      <%= hidden_field_tag :product_id, @product.id %>
      <button id='btn-buy' type='button' class="btn btn-success btn-lg btn-block" >
        <span class="glyphicon glyphicon-ok"></span>I want this!
      </button>

      <script>
        var handler = StripeCheckout.configure({
          key: '<%= Rails.configuration.stripe[:publishable_key] %>',
          token: function(token, arg) {
            document.getElementById("stripeToken").value = token.id;
            document.getElementById("stripeEmail").value = token.email;
            document.getElementById("chargeForm").submit();
          }
        });

        document.getElementById('btn-buy').addEventListener('click', function(e){
          handler.open({
            name: 'One Month',
            description: '<%= @product.title %> <%= @product.subtitle %> ($<%= @product.price %>)',
            amount: document.getElementById("amount").value
          });
          e.preventDefault();
        })
      </script>
    <% end %>

    <ul id="details-infobox" class="list-group">
      <li class="list-group-item active clearfix">DETAILS</li>
      <li class="list-group-item"><%= @product.details %></li>
      <li class="list-group-item clearfix">
        <span class="pull-left content-qualifier">Lenght</span>
        <span class="pull-right"><%= @product.lenght %></span>
      </li>
    </ul>
  </aside>
</section>
<footer id="site-footer">
Made by <a href="http://onemonth.com" target="_blank">
<%= image_tag('one-month-logo.svg', id: 'one-month-footer-logo', alt: 'One Month') %>
</a>
</footer>

<!-- Modal -->
<div class="modal fade" id="author-modal">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title"><span class="glyphicon glyphicon-user"></span>About the Teacher</h4>
      </div>
      <div class="modal-body clearfix">
            <div id="modal-left" class="pull-left">
              <p><strong><%= @product.author %></strong></p>

              <%= @product.author_description %>
            </div>
            <div id="modal-right" class="pull-right">
                <%= image_tag(@product.author_image_name, alt: @product.author) %>
            </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

app/views/products/index.html.erb
<article id="details-article" class="col-sm-8">
	<h1 id="article-title">Our Courses</h1>
</article>

<section id="products">
	<% @products.each do |product| %>
		<div class="product clearfix">
		 <a href="product-detail.html">
		  <div class="product-image-container">
		   <img src="<%= asset_path product.thumbnail_image_name %>" alt="<%= product.title %>"/>
		   <span class="product-price">$<%= product.price %></span>
		 </div>
		 <p class="product-title"><%= product.title %></p></a>
		</div>
	<% end %>
</section>

app/views/purchases/show.html.erb
<section id="content-receipt" class="clearfix">
  <div id="receipt-container">
    <div class="dotmatrix left"></div>
    <div id="receipt-content">
      <h4 id="receipt-title">Thank You!</h4>
      <p><strong>RECEIPT</strong></p>
      <div id="receipt-details" class="row clearfix">
        <div class="col-sm-8 receipt-left">
          <p><strong class="font-weight-heavy"><%= @product.title %></strong><br/> <span class="font-weight-light"><%= @product.subtitle %></span></p>
        </div>
        <div class="col-sm-4">
          <%= @product.price %>
        </div>
      </div>

      <a href="<%= @product.download_url %>"><button type="button" class="btn btn-success btn-xs">DOWNLOAD</button></a>
      <footer id="receipt-footer">
        <small>Your purchase is complete. We hope you enjoy it!</small>
      </footer>
    </div>
    <div class="dotmatrix right"></div>
  </div>
  <div id="receipt-shadow"></div>
</section>